import { Inter } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import AppContextProvider from "@/Context/AppContext";
import Header from "@/Components/Header/Header";
import Footer from "@/Components/Footer/Footer";
import { ToastContainer } from "react-toastify";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Gradlers",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppContextProvider>
          <AppRouterCacheProvider>
            <>
              <Header />
              {children}
              <Footer />
              <Toaster
                position="top-right"
                reverseOrder={false}
                toastOptions={{
                  // Define default options
                  duration: 5000,
                  style: {
                    background: "#363636",
                    color: "#fff",
                  },
                  // Default options for specific types
                  success: {
                    duration: 3000,
                    theme: {
                      primary: "green",
                      secondary: "black",
                    },
                  },
                }}
              />
              <ToastContainer />
            </>
          </AppRouterCacheProvider>
        </AppContextProvider>
      </body>
    </html>
  );
}
