import { Inter } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import AppContextProvider from "@/Context/AppContext";
import Header from "@/Components/Header/Header";
import Footer from "@/Components/Footer/Footer";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Gradlers",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppContextProvider>
          <AppRouterCacheProvider>
            <>
              <Header />
              {children}
              <Footer/>
              <ToastContainer/>
            </>
          </AppRouterCacheProvider>
        </AppContextProvider>
      </body>
    </html>
  );
}
